import { SubMenu } from "@/app/Types/adminPanelTypes";

export const generateRoute = (menuItem: SubMenu): string => {
  const routeMap: { [key: string]: string } = {
    "مدیریت استان ها": "provinces",
    "مدیریت شهرها": "cities",
    "مقادیر ثابت": "constants",
    "مدیریت کاربران": "users",
    "مدیریت منو ها": "menus",
    "مدیریت نقش ها": "roles",
    "مدیریت فروشگاه‌ها": "shops",
    "مدیریت برندها": "brands",
    "مدیریت دسته ها": "categories",
    "مشخصه‌های محصول": "product-features",
    "اطلاعات پایه محصولات": "product-info",
    "مشخصه‌های دسته بندی": "category-features",
    "مدیریت برچسب ها": "tags",
    محصولات: "products",
    "فروشندگان محصولات": "product-vendors",
    "محصولات مجاز فروشنده": "vendor-allowed-products",
    "مدیریت پلن اقساط فروشگاه": "installment-plans",
    "تایید محصولات فروشنده": "vendor-product-approval",
    "دسته بندی مجاز فروشنده": "vendor-allowed-categories",
    لیوت: "layout",
    "لیوت تگ": "layout-tags",
    "گزارش فروش": "sales-report",
    "لیست سفارشات": "orders",
    داشبورد: "dashboard",
    "درخواست های مرجوعی": "return-requests",
    "سفارش‌های باز": "open-orders",
    "مدریت درگاه پرداخت": "payment-gateway",
    "مدیریت تخفیف": "discounts",
    "مدیریت پرداخت": "payments",
    "مدیریت کامنت‌ها": "comments",
    "مدیریت تماس با ما": "contact-us",
    "لاگ ورود کاربران": "login-logs",
    "لاگ تغییرات": "change-logs",
    "مدیریت بنرها": "banners",
    "گرید بنرها": "banner-grid",
    "مدیریت اسلایدها": "slides",
    "صفحات داینامیک": "dynamic-pages",
    "مدیریت تبلیفات پاپ آپ": "popup-ads",
    "مدیریت شبکه‌های اجتماعی": "social-media",
    "سوالات متداول": "faq",
    "مدیریت تبلیغات نواری": "strip-ads",
    "نسخه های اپلیکیشن": "app-versions",
    "قالب پیامک ها": "sms-templates",
    "لاگ پیامک ها": "sms-logs",
    "تست صفحه محصول پایه": "test-product-page",
  };

  return routeMap[menuItem.title] || `menu-${menuItem.id}`;
};
